### ISSUE TITLE
Create proper patch to fix 24bit ALSA sound

### ISSUE THREAD

**Issue by warped-rudi** [xbmc-imx6/xbmc#16] opened 2014-02-26 14:23 UTC
On several SoC platforms 24bit audio will produce static. The reason for this is, that the output conversion function in AWConvert.cpp doesn't produce, what the device expects. We added a patch that fixes this. But this is a hack than is incorrect as well.

The problem is the following: The 24bit audio samples are internally represented by 32bit data items. In Windows, when that data item size (32bits in our case) is larger than the sample size (here 24bits), data has to be left-justified. The original code (including the SSE part) is correct for this case. However, ALSA defines it's 24bit format differently. It wants 24bit samples in 32bit data items (aka SNDRV_PCM_FORMAT_S24_LE/BE) to be right-justified. So in order to fix this, we either need to make this conversion platform-dependent or even define a whole new AE_FMT_S24xx which maps to SNDRV_PCM_FORMAT_S24_xx.

**Comment by wolfgar** [comment] 2014-02-26 21:03
Hi rudi,

As we have already discussed, I agree regarding this topic and the root cause of the issue.
Yet I just want to state that the patch we speak about is not enough to solve the issue 
As you have said that the problem is settled on cubox and pandaboard, I just want to make sure that we agree that additional fixes have to be implemented (not only hack changed to proper patch)

**Comment by CrawX** [comment] 2014-03-31 09:38
Using the new [3.10.17](https://github.com/wandboard-org/linux/tree/wandboard_imx_3.10.17_1.0.0_beta) kernel for the wandboard, I also get this issue with the static noise, over HDMI in my case (no passthrough).
This did not happen on 3.0.35 (I assume because of wolfgar/linux@c46effcfbfc46b85ebb4ddbfcaf0a832d4993e57 and wolfgar/linux@c40e96f637ec499c49cf267c6469d3249ff68552).

However, those two files do not exist on the newer kernel. I looked around the source and found `soc/codecs/omap-hdmi.c`and `soc/codecs/sgtl5000.c`, I'm going to try to disable the 24 bit samples there.

Is this how I'd have to fix this issue at the moment?
I'd appreciate any input on this!

**Comment by warped-rudi** [comment] 2014-03-31 10:39
Not tested though, but you can try to temporary disable 20 and 24bit formats in: https://github.com/wandboard-org/linux/blob/wandboard_imx_3.10.17_1.0.0_beta/sound/soc/mxs/mxs-pcm.c#L39

AFAIK, the 3.0.35 kernel did not spport 24bit operations at all. Therefore, the problem did not show up.

**Comment by warped-rudi** [comment] 2014-04-18 16:01
With #59 applied we should be able to remove the temporary workarounds that restrict the bit depth to 16 from kernel 3.10.xx code.

**Comment by wolfgar** [comment] 2014-04-18 17:53
Even better, we should be able to remove these workarounds from any kernel (3.0.35 and 3.10 or whatever other exotic variant) ;-)

**Comment by wolfgar** [comment] 2014-04-27 14:50
I close this issue now that Rudi's fix is merged
Thanks again...

**Closed as completed by wolfgar** 2014-04-27 14:50 UTC
Labels: bug
