### ISSUE TITLE
Audio stops working

### ISSUE THREAD

**Issue by smallint** [xbmc-imx6/xbmc#20] opened 2014-02-27 09:40 UTC
This is actually quite a show stopper for LiveTV. Haven't noticed this behaviour on recorded streams so far. Two issues (might correlate or not):
1. Audio does not play at all after opening a live stream but playback is OK
2. Audio stops after a while whereas "while" ranges from some seconds to several minutes. This causes the playback to hang for a second, render a frame, hang for a second, render a frame and so on. Only switching to another audio channel helps or more general: to reset the audio processor.

I found lots of references and reports but nobody (to my knowledge) really confirmed/could reproduce/is working on it. Since we are all dealing with the same hardware we should be able to reproduce this behaviour although it occurs sometimes very frequently and sometimes almost never. I am using audio via HDMI. Am I the only one with this problem?

**Comment by koying** [comment] 2014-02-27 15:37
Haven't got this, but I haven't tried live streams, either.
I'll see if I can reproduce with, e.g., the Youtube addon.

**Comment by smallint** [comment] 2014-02-27 18:19
The logs always look like this:

19:16:22 T:1219490896 WARNING: CDVDMessageQueue(audio)::Get - asked for new data packet, with nothing available
19:16:25 T:1219490896 WARNING: Previous line repeats 8 times.
19:16:25 T:1219490896   ERROR: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
19:16:26 T:1219490896   ERROR: Previous line repeats 1 times.
19:16:26 T:1219490896   ERROR: AddPackets - failed to add leftover bytes to render
19:16:27 T:1219490896   ERROR: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
19:16:28 T:1219490896   ERROR: Previous line repeats 1 times.
19:16:28 T:1219490896   ERROR: AddPackets - failed to add leftover bytes to render
19:16:30 T:1219490896   ERROR: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
19:16:31 T:1219490896   ERROR: Previous line repeats 1 times.
19:16:31 T:1219490896   ERROR: AddPackets - failed to add leftover bytes to render
19:16:32 T:1219490896   ERROR: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
19:16:33 T:1219490896   ERROR: Previous line repeats 1 times.
19:16:33 T:1219490896   ERROR: AddPackets - failed to add leftover bytes to render
19:16:34 T:1219490896   ERROR: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
19:16:36 T:1219490896   ERROR: Previous line repeats 1 times.
19:16:36 T:1219490896   ERROR: AddPackets - failed to add leftover bytes to render
19:16:37 T:1219490896   ERROR: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
19:16:38 T:1219490896   ERROR: Previous line repeats 1 times.
19:16:38 T:1219490896   ERROR: AddPackets - failed to add leftover bytes to render
19:16:39 T:1219490896   ERROR: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
19:16:40 T:1219490896   ERROR: Previous line repeats 1 times.
19:16:40 T:1219490896   ERROR: AddPackets - failed to add leftover bytes to render
19:16:42 T:1219490896   ERROR: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer

Will try to catch some debug logs ...

**Comment by smallint** [comment] 2014-02-27 18:36
Cool, it doesn't log anything to debug :(
EDIT: Found this line only:
CDVDPlayerAudio:: Discontinuity1 - was:4127741.910572, should be:2776765.667000, error:-1350976.243572
and so on ... always after "timeout adding data to renderer"

**Comment by wolfgar** [comment] 2014-02-27 20:10
Hi,
I mostly use analog output during my tests (mix use of livetv and rips) and I have never been hit by this issue so it might be specific to hdmi output : to be confirmed of course...

**Comment by smallint** [comment] 2014-03-01 18:08
It is not specific to hmdi, had it as well with analog output. It (almost) always happens when the player needs to buffer more data. Don't know why in LiveTV it is running out of buffer but it does, then this buffer box appears and probably 2 seconds later audio gets stuck. This is a reproducible bug. I tried buffer settings of 20, 30 or even 50: did not help.

```
19:04:18 T:1020261456   ERROR: CEngineStats::UpdateSinkDelay - inconsistency in buffer time
19:04:23 T:1262482512   ERROR: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
19:04:24 T:1262482512   ERROR: Previous line repeats 1 times.
19:04:24 T:1262482512   ERROR: AddPackets - failed to add leftover bytes to render
```

**Comment by smallint** [comment] 2014-03-01 23:11
For anyone who is able to test it. Here is a 100% reproducible case (with my setup):
- connect a usb drive that puts itself into sleep after several minutes
- play a movie from that device
- pause the playback and wait until the device falls asleep
- continue playback -> audio gets stuck
- switch audio channel -> playback recovers

**Comment by smallint** [comment] 2014-03-05 12:09
I am going to test that with the new beta. In case the problem persists could anyone please try to reproduce it?

**Comment by wolfgar** [comment] 2014-03-05 21:12
OK I am formatting an old disk to put it in an external USB case and give it a try if you reproduce...

**Comment by koying** [comment] 2014-03-06 14:47
Looks like ALSA gets stuck/locked.
Could it be related to the the dma issues we have using an usb drive?

**Comment by smallint** [comment] 2014-03-06 18:10
Could be but it also happens when LiveTV is running without accessing an  USB drive (though a USB stick) and only during buffering. Since I have seen various similar reports for different platforms I would argue that it is not specific to IMX6 but it seems very hard to reproduce.

**Comment by smallint** [comment] 2014-03-06 21:45
Yippie, the current version does not exhibit this problem anymore. I tried all known ways to crash the audio and nothing worked. Thanks to the audio subsystem guys. ;)

**Comment by wolfgar** [comment] 2014-03-06 21:53
cool !
Well I have revived a hard disk at least ;)
So I close this bug...

**Closed as completed by wolfgar** 2014-03-06 21:53 UTC
Labels: bug
